Ijm shared folder edits
EcohydrologyTeam/ClearWater-modules pull request #32
Opened 2023-10-06 14:28 UTC by imscw95

Moved the tsm specific processes from shared folder into a tsm_processes folder. Deleted the tsm specific dynamic variables in the shared folder, which appeared to have a different convention than the other dynamic variables, and weren't being called by the tsm model. Verified that model still runs by running the notebook. To me, it looks like the tsm can stand alone. It does have it's own state variable file on the same directory level as the processes and other variables, which is different than nsm. Let me know what you think of this small change. Seems like the priority should be linking the tsm with the CWR and then we can figure out how to pull shared variables like use_sed_flux options, etc.

2023-10-10 15:10 UTC, xaviernogueira commented
Hey once my new PR #33 goes thru, which renames to "clearwater_modules", closing issue #17 you should update from main and update any references to "clearwater_modules_python" to "clearwater_modules".

2023-10-10 21:27 UTC, xaviernogueira requested changes
Thanks for tackling this! 

One change requested however but, mind switching the file naming back to `tsm.processes` instead of `tsm.tsm_processes`. It's generally best practice to not had redundant naming, the path of a file (i.e., the directory it is within) provides info that does not need to be repeated in the file name!

For example, let's say we are making a program that can do a variety of read/write tasks to a variety of file types. We would structure like:

`my_program` - top level directory
     - `my_program\csv` - for csv functions
     - `my_program\xlsx` - for .xlsx functions

Then in both `my_program\csv` and `my_program\xlsx` we would have the the same named python files, for example:  `read_functions.py`, `write_functions.py`, and `utility_functions.py` OR even just `read.py`, `write.py`, and `utility.py`.

The idea here, is that is there are files that serve the same purpose in different directories (as in `processes.py`), they should have the same name and be discriminated by their location in the repo. Does that make sense?

PS also can you undo your edits on the jupyter notebook, they will conflict with updates I made for it.

2023-10-10 21:27 UTC, xaviernogueira commented on examples/model_architecture.ipynb
So I updated this notebook, can you revert the changes to the notebook done in your commits?

2023-10-10 21:27 UTC, xaviernogueira commented on src/clearwater_modules_python/nsm1/state_variables.py
Mind explaining this change to me? 

`tsm.tsm_process` seems a bit redundant.

2023-10-10 21:27 UTC, xaviernogueira commented on src/clearwater_modules_python/nsm1/state_variables.py
See my main comment where I elaborated.

2023-10-11 01:12 UTC, imscw95 commented on src/clearwater_modules_python/nsm1/state_variables.py
Gotcha, so it won't be a problem to import `nsm.carbon.processes` and `tsm.processes` into the same file? In that situation I assume we'd have to "import as" so that the `processes` can be differentiated, right? Or would python know which of the processes is being called based on the function name (i.e. processes.t_water_c exists in the tsm\processes and not the nsm\carbon\processes). Will need to change to that convention for all the nsm folders we have made then too.

2023-10-11 01:32 UTC, imscw95 commented on src/clearwater_modules_python/nsm1/state_variables.py
I assume the same convention for the `dynamic_variables_carbon` etc. Same question though if we're importing multiple `dynamic_variables` into a processes file how are we differentiating them when they are actually called?

2023-10-11 02:51 UTC, xaviernogueira commented on src/clearwater_modules_python/nsm1/state_variables.py
Exactly! If there are different `processes.py` files being imported you can use "import as" to differentiate or just import the directory like "import clearwater_modules.tsm as tsm" then do "tsm.processes".

Either works, the second is probably better. I'll leave it to you.

2023-10-11 14:49 UTC, xaviernogueira commented on src/clearwater_modules_python/nsm1/state_variables.py
@imscw95 Looking at your most recent commit [c240ccb](https://github.com/EcohydrologyTeam/ClearWater-modules-python/pull/32/commits/c240ccbe14f47a62200d3a089dec36211b0c2ead) the TSM stuff looks ready to go (and is passing all the tests).

I see on the NSM side you still import `tsm.tsm_processes`, and since there is no test for that it is not captured. Could you make that final small change (maybe search the repo for "tsm_processes"), and then I think we can merge this one in!

2023-10-11 18:49 UTC, xaviernogueira approved these changes

2023-10-11 21:04 UTC, merged